import { NextResponse } from "next/server";
import { fetchMarketOverviewServer } from "@/core/market/market-server";
import type { SignalAlert } from "@/core/signal/signal-types";

const DEFAULT_SIGNAL_URL = "https://lyra-signal-vercel.vercel.app";
const LOCAL_PRODUCTS = ["SOL-USD", "BTC-USD", "ETH-USD"] as const;

export async function GET(request: Request) {
  const { searchParams } = new URL(request.url);
  const limit = Math.min(Math.max(Number(searchParams.get("limit") ?? 20), 1), 100);
  const upstreamBase = resolveSignalHttpUrl();

  if (upstreamBase) {
    try {
      const response = await fetch(`${upstreamBase}/api/signals/recent?limit=${limit}`, {
        cache: "no-store",
        signal: AbortSignal.timeout(2_500),
      });
      const json = (await response.json()) as unknown;
      if (!response.ok) throw new Error(`Signal worker ${response.status}`);
      return NextResponse.json(json, { headers: { "Cache-Control": "no-store" } });
    } catch (error) {
      console.error("Signal recent proxy failed:", error);
    }
  }

  const signals = await buildLocalSignals(limit);
  return NextResponse.json({ ok: true, signals, source: "lyra" }, { headers: { "Cache-Control": "no-store" } });
}

function resolveSignalHttpUrl() {
  const raw = (process.env.LYRA_SIGNAL_URL || process.env.NEXT_PUBLIC_LYRA_SIGNAL_URL || DEFAULT_SIGNAL_URL)
    .trim()
    .replace(/\/+$/, "")
    .replace(/\/feed$/, "");
  if (!raw) return "";
  if (raw.startsWith("wss://")) return raw.replace(/^wss:\/\//, "https://");
  if (raw.startsWith("ws://")) return raw.replace(/^ws:\/\//, "http://");
  return raw;
}

async function buildLocalSignals(limit: number): Promise<SignalAlert[]> {
  const results = await Promise.allSettled(LOCAL_PRODUCTS.map(toLocalSignal));
  return results.flatMap((result) => (result.status === "fulfilled" ? [result.value] : [])).slice(0, limit);
}

async function toLocalSignal(productId: string): Promise<SignalAlert> {
  const overview = await fetchMarketOverviewServer(productId);
  const symbol = productId.replace(/-USD$/i, "");
  const changePct = overview.open24h > 0 ? ((overview.price - overview.open24h) / overview.open24h) * 100 : 0;
  const sizeUsd = Math.max(overview.volume24h, 0);
  const createdAt = new Date().toISOString();

  return {
    id: `lyra-${symbol.toLowerCase()}-${Math.floor(Date.now() / 60_000)}`,
    primaryRule: "trending_breakout",
    severity: Math.abs(changePct) >= 2 ? "alert" : "notable",
    score: Math.round(Math.min(95, Math.max(55, Math.abs(changePct) * 18 + 55))),
    sentence: `${symbol} market scan: ${changePct >= 0 ? "+" : ""}${changePct.toFixed(2)}% over 24h at $${overview.price.toLocaleString("en-US")}`,
    createdAt,
    event: {
      token: symbol,
      wallet: "lyra",
      action: changePct >= 0 ? "buy" : "sell",
      sizeUsd,
      timestampMs: Date.now(),
      source: "birdeye",
      metadata: {
        birdeye: {
          signalType: "trending_breakout",
          symbol,
          name: symbol,
          priceUsd: overview.price,
          volume1hUsd: overview.volume24h / 24,
          price24hChangePercent: changePct,
          note: "Generated by Lyra signal scan.",
        },
      },
    },
  };
}
